vich_uploader:
    db_driver: orm

    mappings:
       documentation_files:
           uri_prefix: /files/documentation
           upload_destination: '%kernel.project_dir%/public/files/documentation'

           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
